import {and,desc,eq,gt,lt} from "drizzle-orm";
import {getDb} from "../../../../../db";
import {serviceProfiles,serviceRecruits} from "../../../../../db/schema";
import {getChatGPTUser} from "../../../../chatgpt-auth";
import {containsProhibitedContent,prohibitedContentMessage} from "../../../../../lib/content-policy";
import {checkRateLimit,rateLimitResponse} from "../../../../../lib/rate-limit";
import {cleanText,isServiceId,serviceConfig,stringList} from "../../../../../lib/service-config";

async function getContext(params:Promise<{service:string}>){const {service}=await params;if(!isServiceId(service))return null;const user=await getChatGPTUser();return user?{service,user}:null}
function output(row:typeof serviceRecruits.$inferSelect){return {...row,desiredRoles:JSON.parse(row.desiredRoles) as string[]}}

export async function GET(request:Request,{params}:{params:Promise<{service:string}>}){const {service}=await params;if(!isServiceId(service))return Response.json({error:"サービスIDが不正です"},{status:404});const url=new URL(request.url),before=Number(url.searchParams.get("before")||0),now=new Date();const rows=await getDb().select().from(serviceRecruits).where(and(eq(serviceRecruits.serviceId,service),eq(serviceRecruits.status,"open"),gt(serviceRecruits.expiresAt,now),before?lt(serviceRecruits.id,before):undefined)).orderBy(desc(serviceRecruits.id)).limit(31);return Response.json({recruits:rows.slice(0,30).map(output),nextBefore:rows.length>30?rows[29].id:null})}

export async function POST(request:Request,{params}:{params:Promise<{service:string}>}){const ctx=await getContext(params);if(!ctx)return Response.json({error:"ログインまたはサービスIDを確認してください"},{status:401});const limit=await checkRateLimit(`${ctx.service}:${ctx.user.userId}`,{action:"service-recruit",limit:8,windowMs:30*60_000});if(!limit.allowed)return rateLimitResponse(limit.retryAfter);const db=getDb(),[profile]=await db.select().from(serviceProfiles).where(and(eq(serviceProfiles.serviceId,ctx.service),eq(serviceProfiles.userId,ctx.user.userId),eq(serviceProfiles.status,"active"))).limit(1);if(!profile||profile.suspendedAt)return Response.json({error:"先にこのサービスのプロフィールを登録してください"},{status:403});const body=await request.json().catch(()=>({})) as Record<string,unknown>,config=serviceConfig[ctx.service],mode=cleanText(body.mode,40),partySize=typeof body.partySize==="number"&&Number.isInteger(body.partySize)?body.partySize:0,desiredRoles=stringList(body.desiredRoles,5),note=cleanText(body.note,160),startAt=typeof body.startAt==="string"&&body.startAt?new Date(body.startAt):null,minutes=typeof body.durationMinutes==="number"?Math.min(1440,Math.max(15,body.durationMinutes)):120;if(!config.modes.has(mode)||partySize<2||partySize>5||desiredRoles.some(role=>!config.roles.has(role))||(startAt&&Number.isNaN(startAt.getTime())))return Response.json({error:"募集条件を確認してください"},{status:400});if(containsProhibitedContent(note))return Response.json({error:prohibitedContentMessage},{status:400});const now=new Date(),[row]=await db.insert(serviceRecruits).values({serviceId:ctx.service,ownerProfileId:profile.id,mode,partySize,desiredRoles:JSON.stringify(desiredRoles),startAt,note,status:"open",expiresAt:new Date(now.getTime()+minutes*60_000),createdAt:now,updatedAt:now}).returning();return Response.json({recruit:output(row)},{status:201})}
