"use client";
import {useState} from "react";
import styles from "./identity-preview.module.css";
type Tab="find"|"recruit"|"chat"|"profile";
export default function IdentityPreview(){const [logged,setLogged]=useState(false),[tab,setTab]=useState<Tab>("find"),[notice,setNotice]=useState("");const say=(x:string)=>{setNotice(x);setTimeout(()=>setNotice(""),1800)};
 if(!logged)return <main className={styles.app}><div className={styles.login}><section className={styles.hero}><div className={styles.seal}>荘</div><small>SHOEN MATE</small><h1>荘園メイト</h1><p>陣営、段位、得意な役割、遊べる時間から、第五人格を一緒に遊ぶ仲間を探す非公式コミュニティ。</p><div className={styles.figures}><i>救</i><i>牽</i><i>解</i></div></section><section className={styles.sheet}><small>SELECT ACCOUNT</small><h2>アカウントを選んで続ける</h2><p>登録済みの方は、以前使用したアカウントを選んでください。</p>{[["D","Discord","#5865f2"],["𝕏","X","#181818"],["L","LINE","#06c755"]].map(x=><button key={x[1]} onClick={()=>setLogged(true)}><b style={{background:x[2]}}>{x[0]}</b><span><strong>{x[1]}で続ける</strong><small>アカウントを選択してログイン</small></span><em>›</em></button>)}<p className={styles.consent}>続けることで<a href="/legal?service=shoenmate">利用条件・安全方針</a>と<a href="/privacy">プライバシーポリシー</a>に同意します。</p></section></div></main>;
 const nav:[Tab,string,string][]=[["find","⌕","さがす"],["recruit","＋","募集"],["chat","✉","やりとり"],["profile","♙","マイページ"]];return <main className={styles.app}><div className={styles.shell}><header className={styles.header}><div className={styles.brand}><b>荘</b><span><strong>荘園メイト</strong><small>SHOEN MATE</small></span></div><button onClick={()=>say("お知らせはありません")}>♢</button></header>
 {tab==="find"&&<><div className={styles.title}><small>DISCOVER</small><h1>一緒に遊ぶ人を探す</h1></div><article className={styles.card}><div className={styles.portrait}><span className={styles.online}>● オンライン</span><div className={styles.silhouette}>占</div></div><div className={styles.profile}><h2>夜庭のリオ</h2><p>グリフォンⅡ・サバイバー中心・VCあり</p><div className={styles.tags}><span>救助</span><span>チェイス</span><span>ランク戦</span><span>平日夜</span></div><p>勝ち負けより雰囲気重視。連携を相談しながら楽しく回せる方を探しています。</p><div className={styles.actions}><button onClick={()=>say("いいねを送りました")}>♡ いいね</button><button onClick={()=>{say("メイト申請を送りました");setTab("chat")}}>封蝋で申請</button></div></div></article></>}
 {tab==="recruit"&&<><div className={styles.title}><small>RECRUIT</small><h1>現在の募集</h1></div><article className={`${styles.panel} ${styles.recruit}`}><header><strong>ランク戦・サバイバー</strong><small>2分前</small></header><h2>あと2人募集</h2><p>グリフォン帯／救助職歓迎／22:00から／VC任意</p><button className={styles.primary} onClick={()=>say("参加申請を送りました")}>募集へ参加する</button></article><article className={`${styles.panel} ${styles.recruit}`}><header><strong>協力狩り</strong><small>8分前</small></header><h2>楽しく遊べる方</h2><p>段位不問／初心者歓迎／今から</p></article></>}
 {tab==="chat"&&<><div className={styles.title}><small>MESSAGES</small><h1>やりとり</h1></div>{[["占","夜庭のリオ","申請ありがとうございます！何時から行けますか？"],["傭","Noir","また今度ランク戦行きましょう"]].map(x=><article className={`${styles.panel} ${styles.chat}`} key={x[1]} onClick={()=>say(`${x[1]}さんとのチャットを開きます`)}><span>{x[0]}</span><div><strong>{x[1]}</strong><small>{x[2]}</small></div><b>›</b></article>)}</>}
 {tab==="profile"&&<><div className={styles.title}><small>MY PAGE</small><h1>プロフィール</h1></div><article className={styles.panel}><h2>白薔薇</h2><p>マンモスⅠ・サバイバー中心</p><div className={styles.tags}><span>救助</span><span>補助</span><span>休日夜</span></div><p>連携アカウント、公開範囲、通知、ブロック、退会をここから管理できます。</p><button className={styles.primary} onClick={()=>say("プロフィール編集を開きます")}>プロフィールを編集</button></article></>}
 <nav className={styles.nav}>{nav.map(x=><button key={x[0]} className={tab===x[0]?styles.active:""} onClick={()=>setTab(x[0])}><b>{x[1]}</b>{x[2]}</button>)}</nav>{notice&&<div className={styles.notice}>{notice}</div>}<footer className={styles.disclaimer}>本サービスはNetEase GamesおよびIdentity V／第五人格の公式サービスではありません。<br/><a href="/legal?service=shoenmate">規約・安全方針を見る</a></footer></div></main>}
