"use client";
import{useEffect,useState}from"react";
import styles from"./brawl-preview.module.css";
import ServiceOnboarding from"../service-onboarding";
type Tab="find"|"team"|"chat"|"me";
type Profile={displayName:string;gameIdentity:string;skillTier:string;roles:string[];playTimes:string[];bio:string;avatarUrl:string};
const nav:{id:Tab;icon:string;label:string}[]=[{id:"find",icon:"⌕",label:"さがす"},{id:"team",icon:"+",label:"募集"},{id:"chat",icon:"□",label:"やりとり"},{id:"me",icon:"○",label:"マイページ"}];
export default function BrawlPreview(){
 const[auth,setAuth]=useState<"checking"|"guest"|"onboarding"|"ready">("checking"),[profile,setProfile]=useState<Profile|null>(null),[suggestedName,setSuggestedName]=useState(""),[tab,setTab]=useState<Tab>("find"),[toast,setToast]=useState(""),[liked,setLiked]=useState(false);
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2200)};
 useEffect(()=>{let live=true;fetch("/api/services/stamate/profile").then(async response=>{const data=await response.json().catch(()=>({}));if(!live)return;if(response.status===401){setAuth("guest");return}if(!response.ok){setAuth("guest");return}setSuggestedName(data.suggestedName||"");if(data.profile){setProfile(data.profile);setAuth("ready")}else setAuth("onboarding")}).catch(()=>live&&setAuth("guest"));return()=>{live=false}},[]);
 if(auth==="checking")return <main className={styles.login}><section className={styles.intro}><div className={styles.mark}>S</div><h1>STAMATE</h1><p>プロフィールを確認しています…</p></section></main>;
 if(auth==="onboarding")return <ServiceOnboarding service="stamate" name="スタメイト" suggestedName={suggestedName} identityLabel="プレイヤー名・タグ" tiers={["未設定","ブロンズ","シルバー","ゴールド","ダイヤモンド","エリート","ミシック","レジェンド","マスター"]} roles={["アタッカー","タンク","サポート","コントロール","指定なし"]} onComplete={value=>{setProfile(value as Profile);setAuth("ready")}}/>;
 if(auth==="guest")return <main className={styles.login}><section className={styles.intro}><div className={styles.mark}>S</div><b>STAMATE <small>スタメイト</small></b><h1>最高のチームは、<br/>相性からつくる。</h1><p>トロフィーだけじゃない。得意な役割、遊びたいモード、プレイ時間からブロスタ仲間を探そう。</p><div className={styles.bubbles}><i>AT</i><i>MI</i><i>RE</i><span>TEAM UP!</span></div></section><section className={styles.sheet}><i/><small>CHOOSE ACCOUNT</small><h2>アカウントを選んで続ける</h2><p>登録済みの方は、以前使ったアカウントを選んでください。</p>{[["D","Discord","discord","#5865f2"],["𝕏","X","twitter","#111"],["L","LINE","line","#06c755"]].map(x=><button key={x[1]} onClick={()=>{location.href=`/api/login/${x[2]}?returnTo=${encodeURIComponent("/brawl-preview")}`}}><b style={{background:x[3]}}>{x[0]}</b><span><strong>{x[1]}で続ける</strong><small>アカウントを選択してログイン</small></span><em>›</em></button>)}<p className={styles.terms}>続けることで<a href="/legal?service=stamate">利用条件・安全方針</a>と<a href="/privacy">プライバシーポリシー</a>に同意します。</p><footer>UNOFFICIAL COMMUNITY SERVICE · BY YUNAMATCH</footer></section></main>;
 const initials=(profile?.displayName||"YOU").slice(0,2).toUpperCase();
 return <main className={styles.app}><header><button onClick={()=>setTab("me")}>{initials}</button><div><span>S</span><b>STAMATE<small>PLAY TOGETHER</small></b></div><button onClick={()=>notify("通知を読み込んでいます")}>♢</button></header><section className={styles.body}>
 {tab==="find"&&<><div className={styles.top}><div><small>FOR YOU</small><h1>仲間を探す</h1></div><button onClick={()=>notify("トロフィー・モード・役割で絞り込めます")}>☷ 絞り込み</button></div><article className={styles.card}><div className={styles.cardhead}><span>● オンライン</span><b>相性 91%</b></div><div className={styles.visual}><i/><i/><span>MI</span><strong>SUPPORT</strong></div><div className={styles.info}><div className={styles.name}><span>MI</span><div><h2>みお #2PP8J</h2><p>総トロフィー 42,680 · 成人 · VCあり</p></div><button>ⓘ</button></div><div className={styles.tags}><span>サポート</span><span>コントローラー</span><span>夜</span></div><p>エンジョイ寄りだけど勝つ時は真剣！ランク一緒に回せる人を探しています。</p><small>✓ プレイヤータグ確認済み · 8分前に更新</small></div><div className={styles.actions}><button onClick={()=>notify("次のプレイヤーを表示します")}>× 次の人</button><button className={liked?styles.liked:""} onClick={()=>{setLiked(true);notify("いいねを送りました")}}>♡ {liked?"送信済み":"いいね"}</button><button onClick={()=>{setTab("chat");notify("メイト申請を送りました")}}>⚡ メイト申請</button></div></article></>}
 {tab==="team"&&<section className={styles.screen}><small>TEAM FINDER</small><h1>今すぐ遊べる募集</h1><article className={styles.recruit}><div><b>ランク</b><time>2分前</time></div><h2>あと1人でスタート</h2><p>目標：レジェンド帯<br/>希望：サポート / タンク<br/>開始：今から · VCあり</p><button onClick={()=>notify("参加申請を送りました")}>この募集に参加</button></article><button className={styles.create} onClick={()=>notify("募集作成画面を開きます")}>＋ 募集を作成</button></section>}
 {tab==="chat"&&<section className={styles.screen}><small>MESSAGES</small><h1>やりとり</h1><article className={styles.pending}><b>⚡</b><div><strong>みおさんへ申請中</strong><p>承認されるとチャットが始まります</p></div><button>•••</button></article>{[["AT","あつし","今日22時からランクどう？","12:40"],["RE","れお","また遊ぼう！","昨日"]].map(x=><article className={styles.message} key={x[1]}><b>{x[0]}</b><div><strong>{x[1]}</strong><p>{x[2]}</p></div><time>{x[3]}</time></article>)}</section>}
 {tab==="me"&&<section className={styles.screen}><div className={styles.profile}><span>{initials}</span><small>MY PROFILE</small><h1>{profile?.displayName}</h1><p>{profile?.skillTier} · {profile?.roles.join(" / ")}</p></div><div className={styles.stats}><article><b>—</b><small>いいね</small></article><article><b>—</b><small>メイト</small></article><article><b>100%</b><small>登録完了</small></article></div><article className={styles.link}><div><strong>プレイヤー情報</strong><small>{profile?.gameIdentity}</small></div><button onClick={()=>setAuth("onboarding")}>編集</button></article><a className={styles.logout} href="/api/auth/signout?callbackUrl=%2Fbrawl-preview">ログアウト</a></section>}
 </section><nav>{nav.map(x=><button key={x.id} className={tab===x.id?styles.active:""} onClick={()=>setTab(x.id)}><b>{x.icon}</b><span>{x.label}</span></button>)}</nav>{toast&&<aside>{toast}</aside>}<div className={styles.disclaimer}>この素材は非公式であり、Supercellによる承認・支援を受けていません。<a href="https://supercell.com/en/fan-content-policy/">Fan Content Policy</a></div></main>
}
