"use client";
import {useState} from "react";
import styles from "./valorant-preview.module.css";
type Provider="discord"|"x"|"line"|"riot"; type Tab="discover"|"recruit"|"chat"|"profile";
const providers:{id:Provider;name:string;mark:string;note:string}[]=[
 {id:"riot",name:"Riot Games",mark:"R",note:"戦績・ランクを本人確認付きで表示"},
 {id:"discord",name:"Discord",mark:"D",note:"VCや普段使うアカウントで続ける"},
 {id:"x",name:"X",mark:"𝕏",note:"Xのアカウントで続ける"},
 {id:"line",name:"LINE",mark:"L",note:"LINEのアカウントで続ける"}];
const tabs:{id:Tab;icon:string;label:string}[]=[{id:"discover",icon:"⌕",label:"さがす"},{id:"recruit",icon:"+",label:"募集"},{id:"chat",icon:"□",label:"やりとり"},{id:"profile",icon:"○",label:"マイページ"}];
export default function ValorantPreviewPage(){
 const[signedIn,setSignedIn]=useState(false),[provider,setProvider]=useState<Provider|null>(null),[tab,setTab]=useState<Tab>("discover"),[toast,setToast]=useState(""),[liked,setLiked]=useState(false);
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2600)};
 const connect=(id:Provider)=>{setProvider(id);setSignedIn(true);setTab("discover");notify(`${providers.find(x=>x.id===id)?.name}で連携しました（デモ）`)};
 if(!signedIn)return <main className={styles.loginPage}>
  <section className={styles.loginHero}><div className={styles.logoMark}>V</div><p className={styles.logo}>V-MATCH <small>バロマッチ</small></p><h1>一緒に勝ちたい人が、<br/>ちゃんと見つかる。</h1><p>ランク・ロール・時間帯から、VALORANTを一緒に遊ぶ仲間を探せます。</p><div className={styles.previewFaces}><span>SO</span><span>RN</span><span>YU</span><b>1,200+ PLAYERS</b></div></section>
  <section className={styles.loginSheet}><span className={styles.sheetHandle}/><p className={styles.kicker}>SELECT ACCOUNT</p><h2>アカウントを選んで続ける</h2><p className={styles.loginCopy}>登録済みの方は同じアカウントを選ぶと、以前のプロフィールを引き継げます。</p><div className={styles.providerGrid}>{providers.map(x=><button key={x.id} className={`${styles.provider} ${styles[x.id]}`} onClick={()=>connect(x.id)}><span>{x.mark}</span><div><strong>{x.name}で続ける</strong><small>{x.note}</small></div><b>›</b></button>)}</div><p className={styles.consent}>続けることで、<a href="/terms">利用規約</a>と<a href="/privacy">プライバシーポリシー</a>に同意します。Riot連携は本人が許可した情報だけを取得し、設定から解除できます。</p><div className={styles.unofficial}>非公式コミュニティサービス · BY YUNAMATCH</div></section>
 </main>;
 return <main className={styles.appPage}>
  <header className={styles.appHeader}><button className={styles.miniAvatar} onClick={()=>setTab("profile")}>SO</button><div className={styles.appBrand}><span>V</span><div><strong>V-MATCH</strong><small>PLAY TOGETHER</small></div></div><button className={styles.bell} onClick={()=>notify("新しいいいねが2件あります")}>♢<b>2</b></button></header>
  <section className={styles.appContent}>
  {tab==="discover"&&<><div className={styles.discoverTop}><div><p>あなたへのおすすめ</p><h1>プレイヤーを探す</h1></div><button onClick={()=>notify("ランク・ロール・時間帯で絞り込めます")}>☷ 絞り込み</button></div><article className={styles.profileCard}><div className={styles.cardTop}><span className={styles.online}>● オンライン</span><b>相性 88%</b></div><div className={styles.agentShape}><span>RN</span><i/><i/><i/></div><div className={styles.cardInfo}><div className={styles.playerTitle}><span>RN</span><div><h2>Rin#TOKYO</h2><p>プラチナ 1 · 20代 · VCあり</p></div><button aria-label="プロフィール詳細">ⓘ</button></div><div className={styles.roleTags}><span>コントローラー</span><span>センチネル</span><span>平日夜</span></div><p className={styles.bio}>コンペ中心。報告はしっかり、雰囲気は柔らかく遊びたいです。負けても引きずりません。</p><small className={styles.riotVerified}>✓ Riot連携済み · 本人の同意によりランク表示</small></div><div className={styles.cardActions}><button onClick={()=>notify("次のプレイヤーを表示します")}>× 次の人</button><button className={liked?styles.liked:""} onClick={()=>{setLiked(true);notify("いいねを送りました。相互いいねでマッチします")}}>♡ {liked?"送信済み":"いいね"}</button><button onClick={()=>{setTab("chat");notify("メイト申請を送りました")}}>⚡ メイト申請</button></div></article></>}
  {tab==="recruit"&&<section className={styles.simpleScreen}><p className={styles.kicker}>FIND A PARTY</p><h1>今すぐ遊べる募集</h1><article className={styles.recruitCard}><div><span>コンペティティブ</span><small>3分前</small></div><h2>あと2人でスタート</h2><p>募集者：ゴールド 2 · コントローラー<br/>開始：今から · VC：Discord</p><button onClick={()=>notify("募集へ参加申請しました")}>この募集に参加</button></article><button className={styles.createRecruit} onClick={()=>notify("募集作成画面を開きます")}>＋ 募集を作成</button></section>}
  {tab==="chat"&&<section className={styles.simpleScreen}><p className={styles.kicker}>MESSAGES</p><h1>やりとり</h1><article className={styles.matchNotice}><span>⚡</span><div><strong>Rinさんへ申請中</strong><p>承認されるとチャットが始まります</p></div><button onClick={()=>notify("申請をキャンセルできます")}>•••</button></article><article className={styles.messageRow}><span>YU</span><div><strong>Yuta#JP1</strong><p>今日21時からコンペ行けます！</p></div><time>12:40</time></article><article className={styles.messageRow}><span>MI</span><div><strong>Mio#GG</strong><p>昨日はありがとうございました</p></div><time>昨日</time></article></section>}
  {tab==="profile"&&<section className={styles.simpleScreen}><div className={styles.profileHero}><span>SO</span><p className={styles.kicker}>MY PROFILE</p><h1>Sora#JP1</h1><p>ゴールド 2 · コントローラー / センチネル</p></div><div className={styles.stats}><article><b>12</b><small>もらったいいね</small></article><article><b>4</b><small>メイト</small></article><article><b>87%</b><small>プロフィール</small></article></div><article className={styles.accountPanel}><div><strong>連携アカウント</strong><small>{providers.find(x=>x.id===provider)?.name}でログイン中</small></div><button onClick={()=>{setSignedIn(false);setProvider(null)}}>ログアウト</button></article><p className={styles.reviewNote}>審査用デモのため、外部サービスへの実際の認証通信は行いません。</p></section>}
  </section>
  <nav className={styles.bottomNav}>{tabs.map(x=><button key={x.id} className={tab===x.id?styles.activeTab:""} onClick={()=>setTab(x.id)}><b>{x.icon}</b><span>{x.label}</span></button>)}</nav>{toast&&<div className={styles.toast}>{toast}</div>}
 </main>
}
