"use client";
import {FormEvent,useEffect,useState} from "react";
import styles from "./valorant-preview.module.css";
import ServiceOnboarding from "../service-onboarding";
type Provider="discord"|"x"|"line"|"riot"; type Tab="discover"|"recruit"|"chat"|"profile";
type Profile={id?:number;displayName:string;gameIdentity:string;skillTier:string;roles:string[];playTimes:string[];bio:string;avatarUrl:string};
type Candidate=Profile&{id:number;age:number;gender:string};
type Connection={id:number;status:string;other:Profile&{id:number};latestMessage:{body:string;createdAt:string}|null};
type Recruit={id:number;mode:string;partySize:number;desiredRoles:string[];note:string;createdAt:string;owner:Profile|null};
type Message={id:number;senderProfileId:number;body:string;createdAt:string};
const providers:{id:Provider;name:string;mark:string;note:string}[]=[
 {id:"riot",name:"Riot Games",mark:"R",note:"戦績・ランクを本人確認付きで表示"},
 {id:"discord",name:"Discord",mark:"D",note:"VCや普段使うアカウントで続ける"},
 {id:"x",name:"X",mark:"𝕏",note:"Xのアカウントで続ける"},
 {id:"line",name:"LINE",mark:"L",note:"LINEのアカウントで続ける"}];
const tabs:{id:Tab;icon:string;label:string}[]=[{id:"discover",icon:"⌕",label:"さがす"},{id:"recruit",icon:"+",label:"募集"},{id:"chat",icon:"□",label:"やりとり"},{id:"profile",icon:"○",label:"マイページ"}];
export default function ValorantPreviewPage(){
 const[auth,setAuth]=useState<"checking"|"guest"|"onboarding"|"ready">("checking"),[profileData,setProfileData]=useState<Profile|null>(null),[suggestedName,setSuggestedName]=useState(""),[tab,setTab]=useState<Tab>("discover"),[toast,setToast]=useState(""),[profiles,setProfiles]=useState<Candidate[]>([]),[connections,setConnections]=useState<Connection[]>([]),[incoming,setIncoming]=useState<Connection[]>([]),[outgoing,setOutgoing]=useState<Connection[]>([]),[recruits,setRecruits]=useState<Recruit[]>([]),[activeChat,setActiveChat]=useState<Connection|null>(null),[messages,setMessages]=useState<Message[]>([]),[message,setMessage]=useState("");
 const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2600)};
 const load=async()=>{const[d,c,r]=await Promise.all([fetch("/api/services/valomatch/discover"),fetch("/api/services/valomatch/connections"),fetch("/api/services/valomatch/recruits")]),[dd,cc,rr]=await Promise.all([d.json(),c.json(),r.json()]);if(d.ok)setProfiles(dd.profiles||[]);if(c.ok){setConnections(cc.connections||[]);setIncoming(cc.incoming||[]);setOutgoing(cc.outgoing||[])}if(r.ok)setRecruits(rr.recruits||[])};
 useEffect(()=>{let live=true;fetch("/api/services/valomatch/profile").then(async response=>{const data=await response.json().catch(()=>({}));if(!live)return;if(response.status===401||!response.ok){setAuth("guest");return}setSuggestedName(data.suggestedName||"");if(data.profile){setProfileData(data.profile);setAuth("ready")}else setAuth("onboarding")}).catch(()=>live&&setAuth("guest"));return()=>{live=false}},[]);
 useEffect(()=>{if(auth==="ready")void load()},[auth]);
 const connect=(id:Provider)=>{if(id==="riot"){notify("Riot連携は審査完了後に利用できます");return}const authProvider=id==="x"?"twitter":id;location.href=`/api/login/${authProvider}?returnTo=${encodeURIComponent("/valorant-preview")}`};
 const current=profiles[0],removeCurrent=()=>setProfiles(value=>value.slice(1));
 async function like(){if(!current)return;const response=await fetch("/api/services/valomatch/likes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetProfileId:current.id})}),data=await response.json();notify(response.ok?(data.matched?"相互いいねでマッチしました！":"いいねを送りました"):data.error||"送信できませんでした");if(response.ok){removeCurrent();void load()}}
 async function requestMate(){if(!current)return;const response=await fetch("/api/services/valomatch/connections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetProfileId:current.id})}),data=await response.json();notify(response.ok?"メイト申請を送りました":data.error||"申請できませんでした");if(response.ok){removeCurrent();setTab("chat");void load()}}
 async function requestTarget(targetProfileId:number){const response=await fetch("/api/services/valomatch/connections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({targetProfileId})}),data=await response.json();notify(response.ok?"参加申請を送りました":data.error||"申請できませんでした");if(response.ok){setTab("chat");void load()}}
 async function act(connectionId:number,action:"accept"|"decline"|"cancel"){const response=await fetch("/api/services/valomatch/connections",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({connectionId,action})}),data=await response.json();notify(response.ok?action==="accept"?"承認しました":"申請を更新しました":data.error||"操作できませんでした");if(response.ok)void load()}
 async function createRecruit(){const mode=prompt("モード（コンペティティブ / アンレート / スイフトプレイ / その他）","コンペティティブ");if(!mode)return;const partySize=Number(prompt("パーティ人数（2〜5）","5")),note=prompt("募集のひとこと（任意）","")||"";const response=await fetch("/api/services/valomatch/recruits",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode,partySize,desiredRoles:[],note,durationMinutes:120})}),data=await response.json();notify(response.ok?"募集を公開しました":data.error||"募集できませんでした");if(response.ok)void load()}
 async function openChat(connection:Connection){setActiveChat(connection);const response=await fetch(`/api/services/valomatch/messages?connectionId=${connection.id}`),data=await response.json();setMessages(response.ok?data.messages||[]:[])}
 async function sendMessage(event:FormEvent){event.preventDefault();if(!activeChat||!message.trim())return;const body=message.trim();setMessage("");const response=await fetch("/api/services/valomatch/messages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({connectionId:activeChat.id,body,clientId:crypto.randomUUID()})}),data=await response.json();if(response.ok)setMessages(value=>[...value,data.message]);else notify(data.error||"送信できませんでした")}
 if(auth==="checking")return <main className={styles.loginPage}><section className={styles.loginHero}><div className={styles.logoMark}>V</div><h1>V-MATCH</h1><p>プロフィールを確認しています…</p></section></main>;
 if(auth==="onboarding")return <ServiceOnboarding service="valomatch" name="バロマッチ" suggestedName={suggestedName} identityLabel="Riot ID（名前#タグ）" tiers={["未設定","アイアン","ブロンズ","シルバー","ゴールド","プラチナ","ダイヤモンド","アセンダント","イモータル","レディアント"]} roles={["デュエリスト","イニシエーター","コントローラー","センチネル","指定なし"]} onComplete={value=>{setProfileData(value as Profile);setAuth("ready")}}/>;
 if(auth==="guest")return <main className={styles.loginPage}>
  <section className={styles.loginHero}><div className={styles.logoMark}>V</div><p className={styles.logo}>V-MATCH <small>バロマッチ</small></p><h1>一緒に勝ちたい人が、<br/>ちゃんと見つかる。</h1><p>ランク・ロール・時間帯から、VALORANTを一緒に遊ぶ仲間を探せます。</p><div className={styles.previewFaces}><span>SO</span><span>RN</span><span>YU</span><b>1,200+ PLAYERS</b></div></section>
  <section className={styles.loginSheet}><span className={styles.sheetHandle}/><p className={styles.kicker}>SELECT ACCOUNT</p><h2>アカウントを選んで続ける</h2><p className={styles.loginCopy}>登録済みの方は同じアカウントを選ぶと、以前のプロフィールを引き継げます。</p><div className={styles.providerGrid}>{providers.map(x=><button key={x.id} className={`${styles.provider} ${styles[x.id]}`} onClick={()=>connect(x.id)}><span>{x.mark}</span><div><strong>{x.id==="riot"?"Riot連携（審査中）":`${x.name}で続ける`}</strong><small>{x.id==="riot"?"承認後に本人確認付き戦績表示を有効化":x.note}</small></div><b>›</b></button>)}</div><p className={styles.consent}>続けることで、<a href="/legal?service=valomatch">利用条件・安全方針</a>と<a href="/privacy">プライバシーポリシー</a>に同意します。Riot連携は審査承認後、本人が許可した情報だけを取得します。</p><div className={styles.unofficial}>非公式コミュニティサービス · BY YUNAMATCH</div></section>
 </main>;
 return <main className={styles.appPage}>
  <header className={styles.appHeader}><button className={styles.miniAvatar} onClick={()=>setTab("profile")}>SO</button><div className={styles.appBrand}><span>V</span><div><strong>V-MATCH</strong><small>PLAY TOGETHER</small></div></div><button className={styles.bell} onClick={()=>notify("新しいいいねが2件あります")}>♢<b>2</b></button></header>
  <section className={styles.appContent}>
  {tab==="discover"&&<><div className={styles.discoverTop}><div><p>あなたへのおすすめ</p><h1>プレイヤーを探す</h1></div><button onClick={()=>void load()}>↻ 更新</button></div>{current?<article className={styles.profileCard}><div className={styles.cardTop}><span className={styles.online}>● プロフィール公開中</span><b>{current.skillTier}</b></div><div className={styles.agentShape}><span>{current.displayName.slice(0,2)}</span><i/><i/><i/></div><div className={styles.cardInfo}><div className={styles.playerTitle}><span>{current.displayName.slice(0,2)}</span><div><h2>{current.displayName}</h2><p>{current.gameIdentity} · {current.gender||`${current.age}歳`}</p></div><button aria-label="プロフィール詳細">ⓘ</button></div><div className={styles.roleTags}>{current.roles.map(role=><span key={role}>{role}</span>)}</div><p className={styles.bio}>{current.bio||"一緒に遊べる仲間を探しています。"}</p><small className={styles.riotVerified}>遊べる時間：{current.playTimes.join(" · ")}</small></div><div className={styles.cardActions}><button onClick={removeCurrent}>× 次の人</button><button onClick={like}>♡ いいね</button><button onClick={requestMate}>⚡ メイト申請</button></div></article>:<section className={styles.simpleScreen}><h1>表示できるプレイヤーがいません</h1><p>時間を置いて更新してください。</p></section>}</>}
  {tab==="recruit"&&<section className={styles.simpleScreen}><p className={styles.kicker}>FIND A PARTY</p><h1>今すぐ遊べる募集</h1>{recruits.length?recruits.map(item=><article className={styles.recruitCard} key={item.id}><div><span>{item.mode}</span><small>{new Date(item.createdAt).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}</small></div><h2>{item.partySize}人パーティー募集</h2><p>募集者：{item.owner?.displayName||"退会ユーザー"} · {item.owner?.skillTier}<br/>希望：{item.desiredRoles.join(" / ")||"指定なし"}<br/>{item.note}</p>{item.owner?.id&&<button onClick={()=>void requestTarget(item.owner!.id!)}>この募集に参加</button>}</article>):<p>現在公開中の募集はありません。</p>}<button className={styles.createRecruit} onClick={createRecruit}>＋ 募集を作成</button></section>}
  {tab==="chat"&&<section className={styles.simpleScreen}><p className={styles.kicker}>MESSAGES</p><h1>やりとり</h1>{incoming.map(item=><article className={styles.matchNotice} key={item.id}><span>⚡</span><div><strong>{item.other.displayName}さんから申請</strong><p>{item.other.skillTier} · {item.other.roles.join(" / ")}</p></div><button onClick={()=>act(item.id,"accept")}>承認</button><button onClick={()=>act(item.id,"decline")}>断る</button></article>)}{outgoing.map(item=><article className={styles.matchNotice} key={item.id}><span>⚡</span><div><strong>{item.other.displayName}さんへ申請中</strong><p>承認されるとチャットが始まります</p></div><button onClick={()=>act(item.id,"cancel")}>取消</button></article>)}{connections.map(item=><button className={styles.messageRow} key={item.id} onClick={()=>void openChat(item)}><span>{item.other.displayName.slice(0,2)}</span><div><strong>{item.other.displayName}</strong><p>{item.latestMessage?.body||"マッチしました。挨拶してみましょう！"}</p></div></button>)}{!incoming.length&&!outgoing.length&&!connections.length&&<p>まだやりとりがありません。</p>}</section>}
  {tab==="profile"&&<section className={styles.simpleScreen}><div className={styles.profileHero}><span>{profileData?.displayName.slice(0,2)}</span><p className={styles.kicker}>MY PROFILE</p><h1>{profileData?.displayName}</h1><p>{profileData?.gameIdentity} · {profileData?.skillTier} · {profileData?.roles.join(" / ")}</p></div><div className={styles.stats}><article><b>—</b><small>もらったいいね</small></article><article><b>{connections.length}</b><small>メイト</small></article><article><b>100%</b><small>プロフィール</small></article></div><article className={styles.accountPanel}><div><strong>プロフィール設定</strong><small>登録内容をいつでも変更できます</small></div><button onClick={()=>setAuth("onboarding")}>編集</button></article><a className={styles.reviewNote} href="/api/auth/signout?callbackUrl=%2Fvalorant-preview">ログアウト</a></section>}
  </section>
  <nav className={styles.bottomNav}>{tabs.map(x=><button key={x.id} className={tab===x.id?styles.activeTab:""} onClick={()=>{setTab(x.id);void load()}}><b>{x.icon}</b><span>{x.label}</span></button>)}</nav>{activeChat&&<div style={{position:"fixed",inset:0,zIndex:300,background:"#fff",padding:24,overflow:"auto"}}><button onClick={()=>setActiveChat(null)}>← 戻る</button><h2>{activeChat.other.displayName}</h2>{messages.map(item=><p key={item.id} style={{padding:12,background:"#f1edff",borderRadius:14}}>{item.body}</p>)}<form onSubmit={sendMessage} style={{position:"fixed",left:16,right:16,bottom:20,display:"flex",gap:8}}><input style={{flex:1,fontSize:16,padding:14,borderRadius:14,border:"1px solid #ddd"}} value={message} maxLength={500} onChange={event=>setMessage(event.target.value)} placeholder="メッセージを入力"/><button style={{padding:"0 18px",border:0,borderRadius:14,background:"#d93c49",color:"#fff"}}>送信</button></form></div>}{toast&&<div className={styles.toast}>{toast}</div>}
 </main>
}
