"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Player = { name:string; gender:"女性"|"男性"|"その他"; avatar:string; color:string; pokemon:string; role:string; matches:number; winRate:number; rank:string; time:string; mic:boolean; note:string; online:boolean };
type Recruit = { id:number; trainerName:string; gender:string; pokemon:string; role:string; matches:number; winRate:number; rank:string; playTime:string; note:string };
const pokemon=["ハピナス","キュワワー","ミュウツーY","ブラッキー","ピカチュウ","アブソル","カメックス","マスカーニャ"];
const players:Player[]=[
 {name:"momo",gender:"女性",avatar:"M",color:"#ff7eb3",pokemon:"ハピナス",role:"サポート型",matches:1842,winRate:58.7,rank:"マスター 1640",time:"21:00〜24:00",mic:true,note:"ゲッコウガと中央キャリーを支えるのが好きです。楽しく勝ちたい！",online:true},
 {name:"haru_27",gender:"女性",avatar:"H",color:"#8b7cff",pokemon:"キュワワー",role:"サポート型",matches:967,winRate:55.2,rank:"マスター 1512",time:"22:00〜深夜",mic:true,note:"アサシン使いさん募集中。VCは慣れたら◎",online:true},
 {name:"YUI",gender:"女性",avatar:"Y",color:"#ffb84d",pokemon:"ミュウツーY",role:"アタック型",matches:2310,winRate:61.4,rank:"マスター 1780",time:"20:00〜23:00",mic:false,note:"学習装置サポさんとデュオ希望。連敗したら休憩派です。",online:false},
 {name:"しろまる",gender:"女性",avatar:"し",color:"#39c6b0",pokemon:"ブラッキー",role:"ディフェンス型",matches:1254,winRate:57.9,rank:"マスター 1588",time:"平日夜・土日",mic:true,note:"前張り任せてください。アタック型メインの方と組みたいです！",online:true},
 {name:"REN",gender:"男性",avatar:"R",color:"#55a6ff",pokemon:"ピカチュウ",role:"アタック型",matches:734,winRate:53.1,rank:"マスター 1420",time:"19:00〜22:00",mic:true,note:"エンジョイ寄り。連携を練習できる方募集！",online:false},
 {name:"あお",gender:"その他",avatar:"あ",color:"#66c56c",pokemon:"カメックス",role:"ディフェンス型",matches:1590,winRate:59.3,rank:"マスター 1692",time:"土日メイン",mic:false,note:"中央の動きに合わせます。ピン多めで連携しましょう。",online:true}
];
const synergy:Record<string,{partner:string;reason:string}>={ゲッコウガ:{partner:"ハピナス",reason:"回復と妨害無効で、ゲッコウガが大胆に攻め続けられる"},ハピナス:{partner:"ゲッコウガ",reason:"ハピナスの支援を活かして一気に相手を倒せる"},アブソル:{partner:"キュワワー",reason:"高い機動力を保ったまま継続回復を受けられる"},ピカチュウ:{partner:"ブラッキー",reason:"足止めした相手へ安全に遠距離火力を重ねられる"},ミュウツーY:{partner:"ハピナス",reason:"耐久と攻撃速度を補い、集団戦の火力を伸ばせる"}};

export default function Home(){
 const[myPokemon,setMyPokemon]=useState("ゲッコウガ"),[wanted,setWanted]=useState("ハピナス"),[minRate,setMinRate]=useState(50),[minMatches,setMinMatches]=useState(0),[womenOnly,setWomenOnly]=useState(true),[onlineOnly,setOnlineOnly]=useState(false),[saved,setSaved]=useState<string[]>([]),[modal,setModal]=useState<Player|null>(null),[toast,setToast]=useState("");
 const[recruits,setRecruits]=useState<Recruit[]>([]),[loading,setLoading]=useState(true),[compose,setCompose]=useState(false),[applyTo,setApplyTo]=useState<Recruit|null>(null),[sending,setSending]=useState(false);
 const recommended=synergy[myPokemon];
 const results=useMemo(()=>players.filter(p=>(wanted==="すべて"||p.pokemon===wanted)&&p.winRate>=minRate&&p.matches>=minMatches&&(!womenOnly||p.gender==="女性")&&(!onlineOnly||p.online)),[wanted,minRate,minMatches,womenOnly,onlineOnly]);
 const notify=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),2400)};
 const loadRecruits=()=>fetch("/api/recruits").then(r=>r.json()).then(d=>setRecruits(d.recruits||[])).finally(()=>setLoading(false));
 useEffect(()=>{loadRecruits()},[]);
 const submitRecruit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSending(true);const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/recruits",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setSending(false);if(r.status===401){location.href=d.signIn;return}if(!r.ok){notify(d.error||"投稿できませんでした");return}setCompose(false);notify("募集を公開しました！");loadRecruits()};
 const submitApplication=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!applyTo)return;setSending(true);const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/applications",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,recruitId:applyTo.id})});const d=await r.json();setSending(false);if(r.status===401){location.href=d.signIn;return}if(!r.ok){notify(d.error||"申請できませんでした");return}setApplyTo(null);window.prompt(`${applyTo.trainerName}さんの連絡先です。コピーしてユナイトに誘ってください！`,d.contact);notify("参加申請を送りました！")};
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brandMark">U</span><span>UNITE<span>MATE</span></span></a><nav><a href="#search">メイトを探す</a><a href="#guide">使い方</a></nav><button className="profileButton" onClick={()=>notify("プロフィール機能はデモ版では準備中です")}>プロフィール <span>›</span></button></header>
  <section className="hero" id="top"><div className="heroCopy"><div className="eyebrow"><i/> ひとりより、ふたりでもっと強く。</div><h1>相性ぴったりの<br/><em>ユナイトメイト</em>を探そう。</h1><p>使っているポケモンと実力を登録して、<br className="desktop"/>一緒にランクを駆け上がる最高のデュオを見つけよう。</p><div className="heroStats"><div><strong>2,840</strong><span>登録トレーナー</span></div><div><strong>438</strong><span>募集中</span></div><div><strong>96%</strong><span>マッチ満足度</span></div></div></div><div className="duoVisual"><div className="spark s1">✦</div><div className="spark s2">✦</div><div className="pokeOrb purple"><span>ゲ</span><b>ゲッコウガ</b><small>スピード型</small></div><div className="plus">＋</div><div className="pokeOrb pink"><span>ハ</span><b>ハピナス</b><small>サポート型</small></div><div className="synergyTag">相性バツグン！</div></div></section>
  <section className="realBoard" id="real"><div className="boardIntro"><div><p className="kicker">LIVE RECRUITING</p><h2>実際のトレーナーと組む</h2><p>募集を投稿すると、ほかのユーザーから参加申請が届きます。</p></div><button className="postButton" onClick={()=>setCompose(true)}>＋ 募集を投稿する</button></div>
   {loading?<div className="boardEmpty">募集を読み込んでいます…</div>:recruits.length===0?<div className="boardEmpty"><b>最初のメイトを募集しよう</b><span>現在公開中の募集はありません。あなたの募集からコミュニティが始まります。</span><button onClick={()=>setCompose(true)}>募集を作成</button></div>:<div className="realGrid">{recruits.map(r=><article className="realCard" key={r.id}><div className="realBadge">● 募集中</div><h3>{r.trainerName}</h3><p className="rankLine">{r.rank} ・ {r.gender}</p><div className="realPokemon"><strong>{r.pokemon}</strong><span>{r.role}</span></div><div className="realStats"><span><b>{r.matches.toLocaleString()}</b> 試合</span><span><b>{r.winRate}%</b> 勝率</span></div><p className="realNote">{r.note}</p><small>◷ {r.playTime}</small><button onClick={()=>setApplyTo(r)}>この人とユナイトする →</button></article>)}</div>}
  </section>
  <section className="finder" id="search"><div className="sectionTitle"><span>02</span><div><p>FIND YOUR MATE</p><h2>サンプルで相性を探す</h2></div><div className="live"><i/> キャラ相性デモ</div></div>
   <div className="searchPanel"><div className="field"><label htmlFor="myPokemon">あなたの使用ポケモン</label><select id="myPokemon" value={myPokemon} onChange={e=>{setMyPokemon(e.target.value);const next=synergy[e.target.value]?.partner;if(next)setWanted(next)}}><option>ゲッコウガ</option>{pokemon.filter(p=>p!=="ゲッコウガ").map(p=><option key={p}>{p}</option>)}</select></div><div className="pairArrow">相性<br/>チェック <b>→</b></div><div className="field"><label htmlFor="wanted">探しているポケモン</label><select id="wanted" value={wanted} onChange={e=>setWanted(e.target.value)}><option>すべて</option>{pokemon.map(p=><option key={p}>{p}</option>)}</select></div><button className="searchButton" onClick={()=>document.getElementById("results")?.scrollIntoView({behavior:"smooth"})}>この条件で探す <span>→</span></button></div>
   {recommended&&<div className="recommendation"><span>✦ おすすめペア</span><b>{myPokemon} × {recommended.partner}</b><p>{recommended.reason}</p><button onClick={()=>setWanted(recommended.partner)}>この組み合わせで探す</button></div>}
   <div className="filterRow"><label>最低勝率 <select value={minRate} onChange={e=>setMinRate(Number(e.target.value))}><option value="0">指定なし</option><option value="50">50%以上</option><option value="55">55%以上</option><option value="60">60%以上</option></select></label><label>最低試合数 <select value={minMatches} onChange={e=>setMinMatches(Number(e.target.value))}><option value="0">指定なし</option><option value="500">500試合〜</option><option value="1000">1,000試合〜</option><option value="1500">1,500試合〜</option></select></label><label className="check"><input type="checkbox" checked={womenOnly} onChange={e=>setWomenOnly(e.target.checked)}/> 女性プレイヤーのみ</label><label className="check"><input type="checkbox" checked={onlineOnly} onChange={e=>setOnlineOnly(e.target.checked)}/> オンラインのみ</label></div>
   <div className="resultsHead" id="results"><div><h3>募集中のトレーナー</h3><span>{results.length}人見つかりました</span></div><button onClick={()=>{setMinRate(0);setMinMatches(0);setWomenOnly(false);setOnlineOnly(false);setWanted("すべて")}}>条件をリセット</button></div>
   <div className="cardGrid">{results.map(player=><article className="playerCard" key={player.name}><div className="cardTop"><div className="avatar" style={{background:player.color}}>{player.avatar}</div><div className="identity"><div><h4>{player.name}</h4>{player.online&&<span className="online">オンライン</span>}</div><p>{player.rank} ・ {player.gender}</p></div><button className={`save ${saved.includes(player.name)?"active":""}`} aria-label="お気に入り" onClick={()=>setSaved(s=>s.includes(player.name)?s.filter(n=>n!==player.name):[...s,player.name])}>♥</button></div><div className="mainPokemon"><div className="miniPoke" style={{background:`${player.color}22`,color:player.color}}>{player.pokemon.slice(0,1)}</div><div><span>メインポケモン</span><b>{player.pokemon}</b><small>{player.role}</small></div></div><div className="metrics"><div><strong>{player.matches.toLocaleString()}</strong><span>試合数</span></div><div><strong>{player.winRate}<small>%</small></strong><span>勝率</span></div></div><p className="note">“{player.note}”</p><div className="availability"><span>◷ {player.time}</span><span>{player.mic?"🎙 VC OK":"💬 チャット"}</span></div><button className="detailButton" onClick={()=>setModal(player)}>プロフィールを見る <span>→</span></button></article>)}{results.length===0&&<div className="empty"><span>◇</span><h3>条件に合うメイトが見つかりませんでした</h3><p>勝率や試合数の条件を少し広げてみてください。</p></div>}</div>
  </section>
  <section className="how" id="guide"><span className="watermark">DUO</span><div><p className="kicker">HOW IT WORKS</p><h2>3ステップで、<br/>最高のデュオが見つかる。</h2></div><div className="steps"><div><b>01</b><span>◇</span><h3>プロフィール登録</h3><p>使用キャラ・試合数・勝率を入力</p></div><div><b>02</b><span>⌕</span><h3>条件で検索</h3><p>欲しい相方のキャラや実力で探す</p></div><div><b>03</b><span>⚡</span><h3>デュオ結成</h3><p>メッセージを送って一緒にプレイ</p></div></div></section>
  <footer><div className="brand"><span className="brandMark">U</span><span>UNITE<span>MATE</span></span></div><p>非公式ファンメイドサービスです。ゲーム運営会社とは関係ありません。</p><small>© 2026 UNITE MATE</small></footer>
  {modal&&<div className="modalBackdrop" onMouseDown={()=>setModal(null)}><div className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}>×</button><div className="avatar large" style={{background:modal.color}}>{modal.avatar}</div><p className="modalLabel">サンプルプロフィール</p><h2>{modal.name}</h2><p>{modal.rank} ・ {modal.gender}</p><div className="modalPair"><span>{myPokemon}</span><b>×</b><span>{modal.pokemon}</span></div><p className="modalNote">{modal.note}</p><button className="messageButton" onClick={()=>{setModal(null);document.getElementById("real")?.scrollIntoView({behavior:"smooth"})}}>実際の募集を見る ⚡</button></div></div>}
  {compose&&<div className="modalBackdrop"><form className="formModal" onSubmit={submitRecruit}><button type="button" className="close" onClick={()=>setCompose(false)}>×</button><p className="kicker">NEW RECRUIT</p><h2>デュオを募集する</h2><div className="formGrid"><label>トレーナー名<input name="trainerName" required maxLength={24}/></label><label>性別<select name="gender"><option>女性</option><option>男性</option><option>その他</option><option>回答しない</option></select></label><label>使用ポケモン<select name="pokemon">{["ゲッコウガ",...pokemon].map(p=><option key={p}>{p}</option>)}</select></label><label>型<select name="role"><option>アタック型</option><option>スピード型</option><option>バランス型</option><option>ディフェンス型</option><option>サポート型</option></select></label><label>試合数<input name="matches" type="number" min="0" required/></label><label>勝率（%）<input name="winRate" type="number" min="0" max="100" step="0.1" required/></label><label>ランク<input name="rank" required placeholder="マスター 1600"/></label><label>プレイ時間<input name="playTime" required placeholder="平日 21:00〜"/></label><label className="wide">ひとこと<textarea name="note" required maxLength={180}/></label><label className="wide">申請した相手に伝える連絡先<input name="contact" required placeholder="Discord ID / ユナイトのトレーナーID"/></label></div><p className="privacyNote">連絡先は募集一覧には表示されません。</p><button className="messageButton" disabled={sending}>{sending?"投稿中…":"ログインして募集を公開"}</button></form></div>}
  {applyTo&&<div className="modalBackdrop"><form className="formModal compact" onSubmit={submitApplication}><button type="button" className="close" onClick={()=>setApplyTo(null)}>×</button><p className="kicker">JOIN REQUEST</p><h2>{applyTo.trainerName}さんと<br/>ユナイトする</h2><label>あなたのトレーナー名<input name="applicantName" required/></label><label>使用ポケモン<select name="pokemon">{["ゲッコウガ",...pokemon].map(p=><option key={p}>{p}</option>)}</select></label><label>メッセージ<textarea name="message" required maxLength={180} placeholder="一緒にランク行きたいです！"/></label><button className="messageButton" disabled={sending}>{sending?"送信中…":"ログインして参加申請"}</button></form></div>}
  {toast&&<div className="toast">✓ {toast}</div>}
 </main>
}
