import { getDb } from "../../../../db";
import {
  accountLinks,
  applicationMessages,
  applications,
  availabilitySlots,
  blocks,
  connectionRatings,
  connections,
  dailyVisitors,
  lobbies,
  lobbyMembers,
  messageFavorites,
  messages,
  profiles,
  profileLikes,
  notificationDismissals,
  mutualLikeMatches,
  presence,
  pushSubscriptions,
  recruitAlerts,
  recruits,
  reports,
  siteVisitors,
  supportTickets,
  serviceAdminAuditLogs,
  serviceBlocks,
  serviceConnections,
  serviceLikes,
  serviceMessages,
  serviceProfiles,
  serviceRecruits,
  serviceReports,
} from "../../../../db/schema";
import { requireAdmin } from "../../../../lib/admin";

export async function GET() {
  if (!(await requireAdmin()))
    return Response.json({ error: "管理者権限が必要です" }, { status: 403 });
  const db = getDb();
  const [
    profileRows,
    accountRows,
    recruitRows,
    profileLikeRows,
    notificationDismissalRows,
    applicationRows,
    applicationMessageRows,
    connectionRows,
    mutualLikeMatchRows,
    messageRows,
    messageFavoriteRows,
    ratingRows,
    lobbyRows,
    lobbyMemberRows,
    blockRows,
    reportRows,
    ticketRows,
    availabilityRows,
    presenceRows,
    pushSubscriptionRows,
    recruitAlertRows,
    visitorRows,
    dailyRows,
    serviceProfileRows,
    serviceRecruitRows,
    serviceConnectionRows,
    serviceLikeRows,
    serviceMessageRows,
    serviceReportRows,
    serviceBlockRows,
    serviceAdminAuditRows,
  ] = await Promise.all([
    db.select().from(profiles),
    db.select().from(accountLinks),
    db.select().from(recruits),
    db.select().from(profileLikes),
    db.select().from(notificationDismissals),
    db.select().from(applications),
    db.select().from(applicationMessages),
    db.select().from(connections),
    db.select().from(mutualLikeMatches),
    db.select().from(messages),
    db.select().from(messageFavorites),
    db.select().from(connectionRatings),
    db.select().from(lobbies),
    db.select().from(lobbyMembers),
    db.select().from(blocks),
    db.select().from(reports),
    db.select().from(supportTickets),
    db.select().from(availabilitySlots),
    db.select().from(presence),
    db.select().from(pushSubscriptions),
    db.select().from(recruitAlerts),
    db.select().from(siteVisitors),
    db.select().from(dailyVisitors),
    db.select().from(serviceProfiles),
    db.select().from(serviceRecruits),
    db.select().from(serviceConnections),
    db.select().from(serviceLikes),
    db.select().from(serviceMessages),
    db.select().from(serviceReports),
    db.select().from(serviceBlocks),
    db.select().from(serviceAdminAuditLogs),
  ]);
  const generatedAt = new Date();
  return new Response(
    JSON.stringify(
      {
        schemaVersion: 4,
        generatedAt: generatedAt.toISOString(),
        profiles: profileRows,
        accountLinks: accountRows,
        recruits: recruitRows,
        profileLikes: profileLikeRows,
        notificationDismissals: notificationDismissalRows,
        applications: applicationRows,
        applicationMessages: applicationMessageRows,
        connections: connectionRows,
        mutualLikeMatches: mutualLikeMatchRows,
        messages: messageRows,
        messageFavorites: messageFavoriteRows,
        connectionRatings: ratingRows,
        lobbies: lobbyRows,
        lobbyMembers: lobbyMemberRows,
        blocks: blockRows,
        reports: reportRows,
        supportTickets: ticketRows,
        availabilitySlots: availabilityRows,
        presence: presenceRows,
        pushSubscriptions: pushSubscriptionRows,
        recruitAlerts: recruitAlertRows,
        siteVisitors: visitorRows,
        dailyVisitors: dailyRows,
        serviceProfiles: serviceProfileRows,
        serviceRecruits: serviceRecruitRows,
        serviceConnections: serviceConnectionRows,
        serviceLikes: serviceLikeRows,
        serviceMessages: serviceMessageRows,
        serviceReports: serviceReportRows,
        serviceBlocks: serviceBlockRows,
        serviceAdminAuditLogs: serviceAdminAuditRows,
      },
      null,
      2,
    ),
    {
      headers: {
        "content-type": "application/json; charset=utf-8",
        "content-disposition": `attachment; filename="yunamatch-backup-${generatedAt.toISOString().slice(0, 10)}.json"`,
        "cache-control": "no-store",
      },
    },
  );
}
