import {and,desc,eq,inArray,or} from "drizzle-orm";
import {getDb} from "../../../../../db";
import {serviceConnections,serviceMessages,serviceProfiles} from "../../../../../db/schema";
import {getChatGPTUser} from "../../../../chatgpt-auth";
import {checkRateLimit,rateLimitResponse} from "../../../../../lib/rate-limit";
import {isServiceId} from "../../../../../lib/service-config";

async function context(params:Promise<{service:string}>){const {service}=await params;if(!isServiceId(service))return null;const user=await getChatGPTUser();if(!user)return null;const [profile]=await getDb().select().from(serviceProfiles).where(and(eq(serviceProfiles.serviceId,service),eq(serviceProfiles.userId,user.userId),eq(serviceProfiles.status,"active"))).limit(1);return profile&&!profile.suspendedAt?{service,user,profile}:null}

export async function GET(_request:Request,{params}:{params:Promise<{service:string}>}){const ctx=await context(params);if(!ctx)return Response.json({error:"プロフィール登録またはログインが必要です"},{status:401});const db=getDb(),rows=await db.select().from(serviceConnections).where(and(eq(serviceConnections.serviceId,ctx.service),eq(serviceConnections.status,"active"),or(eq(serviceConnections.userAProfileId,ctx.profile.id),eq(serviceConnections.userBProfileId,ctx.profile.id)))).orderBy(desc(serviceConnections.createdAt)).limit(101),page=rows.slice(0,100),otherIds=[...new Set(page.map(row=>row.userAProfileId===ctx.profile.id?row.userBProfileId:row.userAProfileId))],connectionIds=page.map(row=>row.id),[profiles,messageRows]=await Promise.all([otherIds.length?db.select().from(serviceProfiles).where(and(eq(serviceProfiles.serviceId,ctx.service),inArray(serviceProfiles.id,otherIds))):[],connectionIds.length?db.select().from(serviceMessages).where(and(eq(serviceMessages.serviceId,ctx.service),inArray(serviceMessages.connectionId,connectionIds))).orderBy(desc(serviceMessages.id)).limit(500):[]]),byId=new Map(profiles.map(row=>[row.id,row])),latestByConnection=new Map<number,typeof serviceMessages.$inferSelect>();for(const message of messageRows)if(!latestByConnection.has(message.connectionId))latestByConnection.set(message.connectionId,message);return Response.json({connections:page.map(row=>{const other=byId.get(row.userAProfileId===ctx.profile.id?row.userBProfileId:row.userAProfileId),latest=latestByConnection.get(row.id);return {id:row.id,createdAt:row.createdAt,other:other?{id:other.id,displayName:other.displayName,skillTier:other.skillTier,roles:JSON.parse(other.roles),avatarUrl:other.avatarUrl}:{id:0,displayName:"退会ユーザー",skillTier:"",roles:[],avatarUrl:""},latestMessage:latest?{body:latest.body,createdAt:latest.createdAt}:null}}),hasMore:rows.length>100})}

export async function POST(request:Request,{params}:{params:Promise<{service:string}>}){const ctx=await context(params);if(!ctx)return Response.json({error:"プロフィール登録またはログインが必要です"},{status:401});const limit=await checkRateLimit(`${ctx.service}:${ctx.user.userId}`,{action:"service-connect",limit:30,windowMs:60*60_000});if(!limit.allowed)return rateLimitResponse(limit.retryAfter);const body=await request.json().catch(()=>({})) as {targetProfileId?:unknown},targetProfileId=typeof body.targetProfileId==="number"&&Number.isInteger(body.targetProfileId)?body.targetProfileId:0;if(!targetProfileId||targetProfileId===ctx.profile.id)return Response.json({error:"相手を確認してください"},{status:400});const db=getDb(),[target]=await db.select().from(serviceProfiles).where(and(eq(serviceProfiles.id,targetProfileId),eq(serviceProfiles.serviceId,ctx.service),eq(serviceProfiles.status,"active"))).limit(1);if(!target||target.suspendedAt)return Response.json({error:"このプロフィールは利用できません"},{status:404});const low=Math.min(ctx.profile.id,target.id),high=Math.max(ctx.profile.id,target.id),pairKey=`${low}:${high}`,now=new Date();await db.insert(serviceConnections).values({serviceId:ctx.service,pairKey,userAProfileId:low,userBProfileId:high,status:"active",createdAt:now}).onConflictDoNothing({target:[serviceConnections.serviceId,serviceConnections.pairKey]});const [row]=await db.select().from(serviceConnections).where(and(eq(serviceConnections.serviceId,ctx.service),eq(serviceConnections.pairKey,pairKey))).limit(1);return Response.json({connection:row},{status:201})}
